let
    // Generate list of decimals starting at 0 and going up to 360, incrementing by +0.01
    Source = List.Generate(() => 0, each _ < 360.00, each _ + 0.01),
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Column1 to Degree" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Degree"}}),
    #"Changed Type to number" = Table.TransformColumnTypes(#"Renamed Column1 to Degree",{{"Degree", type number}}),
    // Bucketed degree headings into groups of 45°
    #"Added Direction" = Table.AddColumn(#"Changed Type to number", "Direction", each if [Degree] = null then null
                                                                                else if [Degree] = 360 then "N"
                                                                                else if [Degree] >= 315 then "NW"
                                                                                else if [Degree] >= 270 then "W"
                                                                                else if [Degree] >= 225 then "SW"
                                                                                else if [Degree] >= 180 then "S"
                                                                                else if [Degree] >= 135 then "SE"
                                                                                else if [Degree] >= 90 then "E"
                                                                                else if [Degree] >= 45 then "NE"
                                                                                else if [Degree] >= 0 then "N"
                                                                                else null, Text.Type)
in
    #"Added Direction"
